from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtCore import QTimer
import cv2
import pandas as pd
from datetime import datetime
import os
import numpy as np
from PIL import Image

cwd = os.getcwd()
master_path = cwd.replace('\\','/') + '/'

class Ui_mainWindow(object):
    def openEnroll(self):
        self.window = QtWidgets.QFrame()
        self.ui = Ui_enrollWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDetail(self):
        self.window = QtWidgets.QFrame()
        self.ui = Ui_detailWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def resetLabel(self):
        self.result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.result.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:white;\n''border-radius:25px')
        self.result.setText('')

    def trainModel(self):
        self.result.setGeometry(QtCore.QRect(250, 415, 305, 51))
        self.result.setStyleSheet('background-color:rgba(0,0,0,0.5);\n''color:white;\n''border-radius:25px')
        self.result.setText('            Trained!')
        self.delay = QTimer()
        self.delay.start(1500)
        self.delay.timeout.connect(self.resetLabel)

    def setupUi(self, mainWindow):
        mainWindow.setObjectName('mainWindow')
        mainWindow.resize(800, 480)
        mainWindow.setStyleSheet('background-color:rgb(255,255,255)')
        font = QtGui.QFont()
        font.setFamily('Segoe UI Semibold')
        font.setPointSize(16)
        self.attendButton = QtWidgets.QPushButton(mainWindow)
        self.attendButton.setGeometry(QtCore.QRect(485, 100, 281, 71))
        self.attendButton.setFont(font)
        self.attendButton.setStyleSheet('text-align:left;\n''border:none;\n''outline:none;')
        self.attendButton.setFlat(True)
        self.attendButton.setObjectName('attendButton')
        self.attendButton.clicked.connect(self.openDetail)
        self.attendButton.clicked.connect(mainWindow.close)
        self.enrollButton = QtWidgets.QPushButton(mainWindow)
        self.enrollButton.setGeometry(QtCore.QRect(490, 0, 281, 71))
        self.enrollButton.setFont(font)
        self.enrollButton.setStyleSheet('text-align:left;\n''outline:none;\n''border:none;')
        self.enrollButton.setFlat(True)
        self.enrollButton.setObjectName('enrollButton')
        self.enrollButton.clicked.connect(self.openEnroll)
        self.enrollButton.clicked.connect(mainWindow.close)
        self.trainButton = QtWidgets.QPushButton(mainWindow)
        self.trainButton.setGeometry(QtCore.QRect(485, 200, 281, 71))
        self.trainButton.setFont(font)
        self.trainButton.setStyleSheet('text-align:left;\n''border:none;\n''outline:none;')
        self.trainButton.setFlat(True)
        self.trainButton.setObjectName('trainButton')
        self.trainButton.clicked.connect(self.trainModel)
        self.quitButton = QtWidgets.QPushButton(mainWindow)
        self.quitButton.setGeometry(QtCore.QRect(490, 300, 281, 71))
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet('text-align:left;\n''border:none;\n''outline:none;')
        self.quitButton.setFlat(True)
        self.quitButton.setObjectName('quitButton')
        self.quitButton.clicked.connect(mainWindow.close)
        font.setPointSize(18)
        self.result = QtWidgets.QLabel(mainWindow)
        self.result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.result.setFont(font)
        self.result.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:white;\n''border-radius:25px')
        font.setFamily('Segoe UI Semilight')
        font.setPointSize(11)
        self.enrollDesc = QtWidgets.QLabel(mainWindow)
        self.enrollDesc.setGeometry(QtCore.QRect(490, 50, 281, 31))
        self.enrollDesc.setFont(font)
        self.enrollDesc.setObjectName('enrollDesc')
        self.attendDesc = QtWidgets.QLabel(mainWindow)
        self.attendDesc.setGeometry(QtCore.QRect(490, 150, 281, 31))
        self.attendDesc.setFont(font)
        self.attendDesc.setObjectName('attendDesc')
        self.modelDesc = QtWidgets.QLabel(mainWindow)
        self.modelDesc.setGeometry(QtCore.QRect(490, 250, 281, 31))
        self.modelDesc.setFont(font)
        self.modelDesc.setObjectName('modelDesc')
        self.quitDesc = QtWidgets.QLabel(mainWindow)
        self.quitDesc.setGeometry(QtCore.QRect(490, 350, 281, 31))
        self.quitDesc.setFont(font)
        self.quitDesc.setObjectName('quitDesc')
        font.setFamily('Arial Black')
        font.setPointSize(32)
        self.logo_1 = QtWidgets.QLabel(mainWindow)
        self.logo_1.setEnabled(True)
        self.logo_1.setGeometry(QtCore.QRect(75, 202, 111, 51))
        self.logo_1.setFont(font)
        self.logo_1.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:rgb(255,255,255);')
        self.logo_1.setObjectName('logo_1')
        font.setFamily('Rage Italic')
        font.setPointSize(55)
        font.setBold(True)
        self.logo_2 = QtWidgets.QLabel(mainWindow)
        self.logo_2.setEnabled(True)
        self.logo_2.setGeometry(QtCore.QRect(160, 180, 161, 101))
        self.logo_2.setFont(font)
        self.logo_2.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:rgb(255,255,255);')
        self.logo_2.setObjectName('logo_2')
        self.enrollIcon = QtWidgets.QLabel(mainWindow)
        self.enrollIcon.setGeometry(QtCore.QRect(425, 30, 41, 41))
        self.enrollIcon.setText('')
        self.enrollIcon.setPixmap(QtGui.QPixmap(master_path + 'Icons/enroll.png'))
        self.enrollIcon.setScaledContents(True)
        self.enrollIcon.setObjectName('enrollIcon')
        self.attendIcon = QtWidgets.QLabel(mainWindow)
        self.attendIcon.setGeometry(QtCore.QRect(425, 130, 41, 41))
        self.attendIcon.setText('')
        self.attendIcon.setPixmap(QtGui.QPixmap(master_path + 'Icons/attend.png'))
        self.attendIcon.setScaledContents(True)
        self.attendIcon.setObjectName('attendIcon')
        self.modelIcon = QtWidgets.QLabel(mainWindow)
        self.modelIcon.setGeometry(QtCore.QRect(425, 230, 41, 41))
        self.modelIcon.setText('')
        self.modelIcon.setPixmap(QtGui.QPixmap(master_path + 'Icons/model.png'))
        self.modelIcon.setScaledContents(True)
        self.modelIcon.setObjectName('modelIcon')
        self.background = QtWidgets.QLabel(mainWindow)
        self.background.setGeometry(QtCore.QRect(0, 0, 401, 481))
        self.background.setStyleSheet('')
        self.background.setText('')
        self.background.setPixmap(QtGui.QPixmap(master_path + 'Icons/home.jpg'))
        self.background.setScaledContents(True)
        self.background.setObjectName('background')
        self.quitIcon = QtWidgets.QLabel(mainWindow)
        self.quitIcon.setGeometry(QtCore.QRect(427, 330, 41, 41))
        self.quitIcon.setText('')
        self.quitIcon.setPixmap(QtGui.QPixmap(master_path + 'Icons/close.png'))
        self.quitIcon.setScaledContents(True)
        self.quitIcon.setObjectName('quitIcon')
        self.line_1 = QtWidgets.QFrame(mainWindow)
        self.line_1.setGeometry(QtCore.QRect(410, 90, 381, 20))
        self.line_1.setLineWidth(2)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName('line_1')
        self.line_2 = QtWidgets.QFrame(mainWindow)
        self.line_2.setGeometry(QtCore.QRect(410, 190, 381, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName('line_2')
        self.line_3 = QtWidgets.QFrame(mainWindow)
        self.line_3.setGeometry(QtCore.QRect(410, 290, 381, 20))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName('line_3')
        self.line_4 = QtWidgets.QFrame(mainWindow)
        self.line_4.setGeometry(QtCore.QRect(410, 390, 381, 20))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName('line_4')
        self.logo_2.raise_()
        self.logo_1.raise_()
        self.result.raise_() 
        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate('mainWindow', 'Frame'))
        self.attendButton.setText(_translate('mainWindow', 'Take Attendance'))
        self.enrollButton.setText(_translate('mainWindow', 'Enroll face'))
        self.logo_1.setText(_translate('mainWindow', 'veri'))
        self.trainButton.setText(_translate('mainWindow', 'Train model'))
        self.logo_2.setText(_translate('mainWindow', ' face'))
        self.quitButton.setText(_translate('mainWindow', 'Quit'))
        self.enrollDesc.setText(_translate('mainWindow', 'Enroll new students with Moodle ID'))
        self.attendDesc.setText(_translate('mainWindow', 'Verify faces to take attendance'))
        self.modelDesc.setText(_translate('mainWindow', 'Train model based on stored faces'))
        self.quitDesc.setText(_translate('mainWindow', 'Close the application'))

class Ui_enrollWindow(object):
    def openMain(self):
        self.window = QtWidgets.QFrame()
        self.ui = Ui_mainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.video_capture.release()
        self.timer.stop()

    def update_frame(self):
        ret, frame = self.video_capture.read()
        self.frame = frame
        if ret:
            frame = cv2.flip(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB), 1)
            image = QImage(frame, frame.shape[1], frame.shape[0], QImage.Format_RGB888)
            self.liveCam.setPixmap(QPixmap.fromImage(image))

    def resetLabel(self):
        self.result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.result.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:white;\n''border-radius:25px')
        self.result.setText('')

    def enrollFace(self):
        try:
            mid = int(self.midLine.text())
            face_cascade = cv2.CascadeClassifier(master_path + 'Data/haarcascade_frontalface_alt2.xml')
            self.frame = cv2.cvtColor(self.frame, cv2.COLOR_BGR2GRAY)
            face = face_cascade.detectMultiScale(self.frame, 1.1, 4)
            for (x, y, w, h) in face:
                face = self.frame[y:y + h, x:x + w] 
            face = cv2.equalizeHist(face)
            face = cv2.resize(face, (640, 640))
            cv2.imwrite(master_path + 'Students/' + str(mid) + '.jpg', face)
            self.result.setGeometry(QtCore.QRect(260, 415, 305, 51))
            self.result.setStyleSheet('background-color:rgba(0,0,0,0.5);\n''color:white;\n''border-radius:25px')
            self.result.setText('          Successful!')
            self.delay = QTimer()
            self.delay.start(1500)
            self.delay.timeout.connect(self.resetLabel)

        except:
            self.result.setGeometry(QtCore.QRect(260, 415, 305, 51))
            self.result.setStyleSheet('background-color:rgba(0,0,0,0.5);\n''color:white;\n''border-radius:25px')
            self.result.setText('             Failed!')
            self.delay = QTimer()
            self.delay.start(1500)
            self.delay.timeout.connect(self.resetLabel)

    def __init__(self):
        super().__init__()
        self.video_capture = cv2.VideoCapture(0)
        self.video_capture.set(cv2.CAP_PROP_FRAME_WIDTH, 400)
        self.video_capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 420)
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_frame)
        self.timer.start(30)

    def setupUi(self, enrollWindow):
        enrollWindow.setObjectName('enrollWindow')
        enrollWindow.resize(800, 480)
        enrollWindow.setStyleSheet('background-color:rgb(255,255,255);')
        font = QtGui.QFont()
        font.setFamily('Segoe UI Semibold')
        font.setPointSize(16)
        self.backButton = QtWidgets.QPushButton(enrollWindow)
        self.backButton.setGeometry(QtCore.QRect(420, 390, 171, 71))
        self.backButton.setFont(font)
        self.backButton.setStyleSheet('background-color:rgb(255,255,255);\n''color:rgb(0,127,255);\n''border-radius:10;\n''border: 3px solid rgb(0,127,255);')
        self.backButton.setObjectName('backButton')
        self.backButton.clicked.connect(self.openMain)
        self.backButton.clicked.connect(enrollWindow.close)
        self.enrollButton = QtWidgets.QPushButton(enrollWindow)
        self.enrollButton.setGeometry(QtCore.QRect(610, 390, 171, 71))
        self.enrollButton.setFont(font)
        self.enrollButton.setStyleSheet('background-color:rgb(0,127,255);\n''color:rgb(255,255,255);\n''border-radius:10;')
        self.enrollButton.setObjectName('enrollButton')
        self.enrollButton.clicked.connect(self.enrollFace)
        self.mid = QtWidgets.QLabel(enrollWindow)
        self.mid.setGeometry(QtCore.QRect(30, 20, 141, 41))
        self.mid.setFont(font)
        self.mid.setObjectName('mid')
        self.midLine = QtWidgets.QLineEdit(enrollWindow)
        self.midLine.setGeometry(QtCore.QRect(180, 20, 221, 41))
        self.midLine.setFont(font)
        self.midLine.setObjectName('midLine')
        font.setPointSize(20)
        self.title = QtWidgets.QLabel(enrollWindow)
        self.title.setGeometry(QtCore.QRect(430, 20, 161, 51))
        self.title.setFont(font)
        self.title.setObjectName('title')
        font.setPointSize(18)
        self.result = QtWidgets.QLabel(enrollWindow)
        self.result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.result.setFont(font)
        self.result.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:white;\n''border-radius:25px')
        self.result.setFrameShape(QtWidgets.QFrame.Box)
        self.result.setObjectName('result')
        self.liveCam = QtWidgets.QLabel(enrollWindow)
        self.liveCam.setGeometry(QtCore.QRect(30, 80, 371, 371))
        self.liveCam.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.liveCam.setText('')
        self.liveCam.setObjectName('liveCam')
        font.setFamily('Segoe UI Semilight')
        font.setPointSize(14)
        self.desc = QtWidgets.QLabel(enrollWindow)
        self.desc.setGeometry(QtCore.QRect(420, 80, 361, 111))
        self.desc.setFont(font)
        self.desc.setObjectName('desc')
        self.line_1 = QtWidgets.QFrame(enrollWindow)
        self.line_1.setGeometry(QtCore.QRect(420, 70, 361, 20))
        self.line_1.setLineWidth(2)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName('line_1')
        self.line_2 = QtWidgets.QFrame(enrollWindow)
        self.line_2.setGeometry(QtCore.QRect(420, 365, 361, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName('line_2')
        self.result.raise_()
        self.retranslateUi(enrollWindow)
        QtCore.QMetaObject.connectSlotsByName(enrollWindow)

    def retranslateUi(self, enrollWindow):
        _translate = QtCore.QCoreApplication.translate
        enrollWindow.setWindowTitle(_translate('enrollWindow', 'Frame'))
        self.backButton.setText(_translate('enrollWindow', 'Back'))
        self.enrollButton.setText(_translate('enrollWindow', 'Enroll'))
        self.mid.setText(_translate('enrollWindow', 'Moodle ID:'))
        self.desc.setText(_translate('enrollWindow', 'Enter your Moodle ID in the above\n''field and press enroll button to save\n''your photo in Database.'))
        self.title.setText(_translate('enrollWindow', 'Enroll face'))

class Ui_detailWindow(object):
    def openAttend(self):
        self.window = QtWidgets.QFrame()
        self.ui = Ui_attendWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def openMain(self):
        self.window = QtWidgets.QFrame()
        self.ui = Ui_mainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def getDetail(self):
        sub = self.subMenu.currentText().replace(' ','')
        time = self.timeMenu.currentText().replace(' ','')
        day = str(datetime.now().day)
        month = str(datetime.now().month)
        match month:
            case '1':
                month = 'Jan'
            case '2':
                month = 'Feb'
            case '3':
                month = 'Mar'
            case '4':
                month = 'Apr'
            case '5':
                month = 'May'
            case '6':
                month = 'Jun'
            case '7':
                month = 'Jul'
            case '8':
                month = 'Aug'
            case '9':
                month = 'Sep'
            case '10':
                month = 'Oct'
            case '11':
                month = 'Nov'
            case '12':
                month = 'Dec'
        date = day +'-'+ month
        col = date +' '+ time
        path = master_path + 'Attendance/' + sub + '.xlsx'
        df = pd.read_csv(master_path + 'Data/tableData.csv')
        df.iloc[0, 0] = sub
        df.iloc[0, 1] = path
        df.iloc[0, 2] = col
        df.to_csv(master_path + 'Data/tableData.csv',index=False)

    def setupUi(self, detailWindow):
        detailWindow.setObjectName('detailWindow')
        detailWindow.resize(800, 480)
        detailWindow.setStyleSheet('background-color:rgb(255,255,255);')
        font = QtGui.QFont()
        font.setFamily('Segoe UI Semibold')
        font.setPointSize(16)
        self.subMenu = QtWidgets.QComboBox(detailWindow)
        self.subMenu.setGeometry(QtCore.QRect(30, 140, 341, 51))
        self.subMenu.setFont(font)
        self.subMenu.setStyleSheet('border:1 solid white;\n''background-color:rgba(0,0,0,0);\n''color:rgb(255,255,255);')
        self.subMenu.setObjectName('subMenu')
        self.subMenu.addItem('')
        self.subMenu.addItem('')
        self.subMenu.addItem('')
        self.subMenu.addItem('')
        self.subMenu.addItem('')
        self.subLine = QtWidgets.QLabel(detailWindow)
        self.subLine.setGeometry(QtCore.QRect(90, 70, 281, 31))
        self.subLine.setFont(font)
        self.subLine.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:rgb(255,255,255);')
        self.subLine.setObjectName('subLine')
        self.timeLine = QtWidgets.QLabel(detailWindow)
        self.timeLine.setGeometry(QtCore.QRect(90, 260, 281, 31))
        self.timeLine.setFont(font)
        self.timeLine.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:rgb(255,255,255);')
        self.timeLine.setObjectName('timeLine')
        self.timeMenu = QtWidgets.QComboBox(detailWindow)
        self.timeMenu.setGeometry(QtCore.QRect(30, 330, 341, 51))
        self.timeMenu.setFont(font)
        self.timeMenu.setStyleSheet('border:1 solid white;\n''background-color:rgba(0,0,0,0);\n''color:rgb(255,255,255);')
        self.timeMenu.setObjectName('timeMenu')
        self.timeMenu.addItem('')
        self.timeMenu.addItem('')
        self.timeMenu.addItem('')
        self.timeMenu.addItem('')
        self.backButton = QtWidgets.QPushButton(detailWindow)
        self.backButton.setGeometry(QtCore.QRect(420, 390, 171, 71))
        self.backButton.setFont(font)
        self.backButton.setStyleSheet('background-color:rgb(255,255,255);\n''color:rgb(0,127,255);\n''border-radius:10;\n''border: 3px solid rgb(0,127,255);')
        self.backButton.setObjectName('backButton')
        self.backButton.clicked.connect(self.openMain)
        self.backButton.clicked.connect(detailWindow.close)
        self.doneButton = QtWidgets.QPushButton(detailWindow)
        self.doneButton.setGeometry(QtCore.QRect(610, 390, 171, 71))
        self.doneButton.setFont(font)
        self.doneButton.setStyleSheet('background-color:rgb(0,127,255);\n''color:rgb(255,255,255);\n''border-radius:10;')
        self.doneButton.setObjectName('doneButton')
        self.doneButton.clicked.connect(self.getDetail)
        self.doneButton.clicked.connect(self.openAttend)
        self.doneButton.clicked.connect(detailWindow.close)
        font.setPointSize(20)
        self.title = QtWidgets.QLabel(detailWindow)
        self.title.setGeometry(QtCore.QRect(430, 20, 111, 41))
        self.title.setFont(font)
        self.title.setObjectName('title')
        font.setFamily('Segoe UI Semilight')
        font.setPointSize(14)
        self.desc = QtWidgets.QLabel(detailWindow)
        self.desc.setGeometry(QtCore.QRect(420, 80, 351, 91))
        self.desc.setFont(font)
        self.desc.setObjectName('desc')
        self.timeDesc = QtWidgets.QLabel(detailWindow)
        self.timeDesc.setGeometry(QtCore.QRect(90, 290, 281, 31))
        font.setPointSize(11)
        self.timeDesc.setFont(font)
        self.timeDesc.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:rgb(255,255,255);')
        self.timeDesc.setObjectName('timeDesc')
        self.subDesc = QtWidgets.QLabel(detailWindow)
        self.subDesc.setGeometry(QtCore.QRect(90, 100, 281, 31))
        self.subDesc.setFont(font)
        self.subDesc.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:rgb(255,255,255);')
        self.subDesc.setObjectName('subDesc')
        self.line_1 = QtWidgets.QFrame(detailWindow)
        self.line_1.setGeometry(QtCore.QRect(420, 60, 361, 20))
        self.line_1.setLineWidth(2)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName('line_1')
        self.line_2 = QtWidgets.QFrame(detailWindow)
        self.line_2.setGeometry(QtCore.QRect(420, 365, 361, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName('line_2')
        self.subIcon = QtWidgets.QLabel(detailWindow)
        self.subIcon.setGeometry(QtCore.QRect(30, 80, 41, 41))
        self.subIcon.setStyleSheet('background-color:rgba(0,0,0,0);')
        self.subIcon.setText('')
        self.subIcon.setPixmap(QtGui.QPixmap(master_path + 'Icons/book.png'))
        self.subIcon.setScaledContents(True)
        self.subIcon.setObjectName('subIcon')
        self.timeIcon = QtWidgets.QLabel(detailWindow)
        self.timeIcon.setGeometry(QtCore.QRect(30, 270, 41, 41))
        self.timeIcon.setStyleSheet('background-color:rgba(0,0,0,0);')
        self.timeIcon.setText('')
        self.timeIcon.setPixmap(QtGui.QPixmap(master_path + 'Icons/time.png'))
        self.timeIcon.setScaledContents(True)
        self.timeIcon.setObjectName('timeIcon')
        self.background = QtWidgets.QLabel(detailWindow)
        self.background.setGeometry(QtCore.QRect(0, 0, 401, 481))
        self.background.setText('')
        self.background.setPixmap(QtGui.QPixmap(master_path + 'Icons/detail.jpg'))
        self.background.setScaledContents(True)
        self.background.setObjectName('background')
        self.line_3 = QtWidgets.QLabel(detailWindow)
        self.line_3.setGeometry(QtCore.QRect(20, 230, 361, 2))
        self.line_3.setText('')
        self.line_3.setObjectName('line_3')
        self.subMenu.raise_()
        self.subLine.raise_()
        self.timeLine.raise_()
        self.timeMenu.raise_()
        self.subIcon.raise_()
        self.timeIcon.raise_()
        self.timeDesc.raise_()
        self.subDesc.raise_()
        self.line_3.raise_()
        self.retranslateUi(detailWindow)
        QtCore.QMetaObject.connectSlotsByName(detailWindow)

    def retranslateUi(self, detailWindow):
        _translate = QtCore.QCoreApplication.translate
        detailWindow.setWindowTitle(_translate('detailWindow', 'Frame'))
        self.subMenu.setItemText(0, _translate('detailWindow', ' ME'))
        self.subMenu.setItemText(1, _translate('detailWindow', ' MCS'))
        self.subMenu.setItemText(2, _translate('detailWindow', ' ICE'))
        self.subMenu.setItemText(3, _translate('detailWindow', ' CCS'))
        self.subMenu.setItemText(4, _translate('detailWindow', ' MIS'))
        self.subLine.setText(_translate('detailWindow', 'Subject'))
        self.timeLine.setText(_translate('detailWindow', 'Time'))
        self.timeMenu.setItemText(0, _translate('detailWindow', ' 11:00'))
        self.timeMenu.setItemText(1, _translate('detailWindow', ' 11:55'))
        self.timeMenu.setItemText(2, _translate('detailWindow', ' 1:20'))
        self.timeMenu.setItemText(3, _translate('detailWindow', ' 2:15'))
        self.desc.setText(_translate('detailWindow', 'Select subject for which attendance\n''has to be taken and choose the \n''respective timeslot. '))
        self.backButton.setText(_translate('detailWindow', 'Back'))
        self.doneButton.setText(_translate('detailWindow', 'Done'))
        self.title.setText(_translate('detailWindow', 'Details'))
        self.timeDesc.setText(_translate('detailWindow', 'Choose a starting time'))
        self.subDesc.setText(_translate('detailWindow', 'Choose a subject'))

class Ui_authWindow(object):
    def openAttend(self):
        self.window = QtWidgets.QFrame()
        self.ui = Ui_attendWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openMain(self):
        self.window = QtWidgets.QFrame()
        self.ui = Ui_mainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def resetLabel(self):
        self.result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.result.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:white;\n''border-radius:25px')
        self.result.setText('')

    def storeAuth(self):
        if self.pinLine.text() == '12345':
            self.openMain()
            self.authWindow.close()
        else:
            self.result.setGeometry(QtCore.QRect(250, 415, 305, 51))
            self.result.setStyleSheet('background-color:rgba(0,0,0,0.5);\n''color:white;\n''border-radius:25px')
            self.result.setText('         Wrong pin!')
            self.delay = QTimer()
            self.delay.start(1500)
            self.delay.timeout.connect(self.resetLabel)

    def setupUi(self, authWindow):
        self.authWindow = authWindow
        authWindow.setObjectName('authWindow')
        authWindow.resize(800, 480)
        authWindow.setStyleSheet('background-color:rgb(255,255,255);')
        font = QtGui.QFont()
        font.setFamily('Segoe UI Semibold')
        font.setPointSize(16)
        self.head = QtWidgets.QLabel(authWindow)
        self.head.setGeometry(QtCore.QRect(50, 20, 301, 51))
        self.head.setFont(font)
        self.head.setStyleSheet('color:rgb(255,255,255);\n''background-color:rgba(0,0,0,0)')
        self.head.setObjectName('head')
        self.pin = QtWidgets.QLabel(authWindow)
        self.pin.setGeometry(QtCore.QRect(90, 90, 281, 41))
        self.pin.setFont(font)
        self.pin.setStyleSheet('color:rgb(255,255,255);\n''background-color:rgba(0,0,0,0)')
        self.pin.setObjectName('pin')
        self.backButton = QtWidgets.QPushButton(authWindow)
        self.backButton.setGeometry(QtCore.QRect(420, 390, 171, 71))
        self.backButton.setFont(font)
        self.backButton.setStyleSheet('background-color:rgb(255,255,255);\n''color:rgb(0,127,255);\n''border-radius:10;\n''border: 3px solid rgb(0,127,255);')
        self.backButton.setObjectName('backButton')
        self.backButton.clicked.connect(self.openAttend)
        self.backButton.clicked.connect(authWindow.close)
        self.doneButton = QtWidgets.QPushButton(authWindow)
        self.doneButton.setGeometry(QtCore.QRect(610, 390, 171, 71))
        self.doneButton.setFont(font)
        self.doneButton.setStyleSheet('background-color:rgb(0,127,255);\n''color:rgb(255,255,255);\n''border-radius:10;')
        self.doneButton.setObjectName('doneButton')
        self.doneButton.clicked.connect(self.storeAuth)
        font.setPointSize(14)
        self.pinLine = QtWidgets.QLineEdit(authWindow)
        self.pinLine.setGeometry(QtCore.QRect(30, 160, 341, 41))
        self.pinLine.setFont(font)
        self.pinLine.setStyleSheet('border:1 solid white;\n''background-color:rgba(0,0,0,0);\n''color:rgb(255,255,255);')
        self.pinLine.setObjectName('pinLine')
        font.setPointSize(20)
        self.title = QtWidgets.QLabel(authWindow)
        self.title.setGeometry(QtCore.QRect(430, 20, 251, 41))
        self.title.setFont(font)
        self.title.setObjectName('title')
        font.setPointSize(18)
        self.result = QtWidgets.QLabel(authWindow)
        self.result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        font.setFamily('Segoe UI Semibold')
        self.result.setFont(font)
        self.result.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:white;\n''border-radius:25px')
        self.result.setFrameShape(QtWidgets.QFrame.Box)
        self.result.setObjectName('result')
        self.line_1 = QtWidgets.QLabel(authWindow)
        self.line_1.setGeometry(QtCore.QRect(20, 70, 361, 1))
        self.line_1.setText('')
        self.line_1.setObjectName('line_1')
        self.line_2 = QtWidgets.QFrame(authWindow)
        self.line_2.setGeometry(QtCore.QRect(420, 365, 361, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName('line_2')
        self.line_3 = QtWidgets.QFrame(authWindow)
        self.line_3.setGeometry(QtCore.QRect(420, 60, 361, 20))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName('line_3')
        font.setFamily('Segoe UI Semilight')
        font.setPointSize(14)
        self.desc = QtWidgets.QLabel(authWindow)
        self.desc.setGeometry(QtCore.QRect(420, 80, 361, 121))
        self.desc.setFont(font)
        self.desc.setObjectName('desc')
        font.setPointSize(11)
        self.pinDesc = QtWidgets.QLabel(authWindow)
        self.pinDesc.setGeometry(QtCore.QRect(90, 120, 281, 31))
        self.pinDesc.setFont(font)
        self.pinDesc.setStyleSheet('color:rgb(255,255,255);\n''background-color:rgba(0,0,0,0)')
        self.pinDesc.setObjectName('pinDesc')
        self.background = QtWidgets.QLabel(authWindow)
        self.background.setGeometry(QtCore.QRect(0, 0, 401, 481))
        self.background.setText('')
        self.background.setPixmap(QtGui.QPixmap(master_path + 'Icons/bars.jpg'))
        self.background.setScaledContents(True)
        self.background.setObjectName('background')
        self.pinIcon = QtWidgets.QLabel(authWindow)
        self.pinIcon.setGeometry(QtCore.QRect(30, 102, 41, 41))
        self.pinIcon.setStyleSheet('background-color:rgba(0,0,0,0)')
        self.pinIcon.setText('')
        self.pinIcon.setPixmap(QtGui.QPixmap(master_path + 'Icons/key.png'))
        self.pinIcon.setScaledContents(True)
        self.pinIcon.setObjectName('pinIcon')
        self.head.raise_()
        self.pin.raise_()
        self.pinLine.raise_()
        self.result.raise_()
        self.pinIcon.raise_()
        self.pinDesc.raise_()
        self.line_1.raise_()
        self.retranslateUi(authWindow)
        QtCore.QMetaObject.connectSlotsByName(authWindow)

    def retranslateUi(self, authWindow):
        _translate = QtCore.QCoreApplication.translate
        authWindow.setWindowTitle(_translate('authWindow', 'Frame'))
        self.head.setText(_translate('authWindow', 'Authentication Required'))
        self.pin.setText(_translate('authWindow', 'Pin'))
        self.backButton.setText(_translate('authWindow', 'Back'))
        self.doneButton.setText(_translate('authWindow', 'Done'))
        self.title.setText(_translate('authWindow', 'Stop attendance'))
        self.desc.setText(_translate('authWindow', 'Enter correct password in order to \n''stop taking attendance, share the \n''recorded attendance and return to \n''main menu. '))
        self.pinDesc.setText(_translate('authWindow', 'Enter admin password'))

class Ui_attendWindow(object):
    def openAuth(self):
        self.window = QtWidgets.QFrame()
        self.ui = Ui_authWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.video_capture.release()
        self.timer.stop()

    def resetLabel(self):
        self.result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.result.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:white;\n''border-radius:25px')
        self.result.setText('')

    def __init__(self):
        super().__init__()
        self.video_capture = cv2.VideoCapture(0)
        self.video_capture.set(cv2.CAP_PROP_FRAME_WIDTH, 400)
        self.video_capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 420)
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_frame)
        self.timer.start(30)
        df = pd.read_csv(master_path + 'Data/tableData.csv')
        sub = df.iloc[0, 0]
        path = df.iloc[0, 1]
        col = df.iloc[0, 2]
        df = pd.read_excel(path)
        df.set_index('MID', drop=False, inplace=True)
        df.loc[:, col] = 0
        df.loc['Total lec', col] = 1
        df.to_excel(path,index=False)

    def update_frame(self):
        ret, frame = self.video_capture.read()
        self.frame = frame
        if ret:
            frame = cv2.flip(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB), 1)
            image = QImage(frame, frame.shape[1], frame.shape[0], QImage.Format_RGB888)
            self.liveCam.setPixmap(QPixmap.fromImage(image))

    def verifyFace(self):
        try:
            train_folder = master_path + 'Students/'
            test_file = master_path + 'Temp/temp.jpg'
            face_cascade = cv2.CascadeClassifier(master_path + 'Data/haarcascade_frontalface_alt2.xml')
            faces = []
            uids = []
            for file in os.listdir(train_folder):
                path = train_folder + file
                uid = int(file.strip('.jpg'))
                img = Image.open(path).convert('L')
                img_np = np.array(img, 'uint8')
                faces.append(img_np)
                uids.append(uid)
            self.frame = cv2.cvtColor(self.frame, cv2.COLOR_BGR2GRAY)
            face = face_cascade.detectMultiScale(self.frame, 1.1, 4)
            for (x, y, w, h) in face:
                face = self.frame[y:y + h, x:x + w] 
            face = cv2.equalizeHist(face)
            face = cv2.resize(face, (640, 640))
            cv2.imwrite(test_file, face)
            model = cv2.face.LBPHFaceRecognizer_create()
            model.train(faces, np.array(uids))
            test_img = Image.open(test_file).convert('L')
            test_np = np.array(test_img, 'uint8')
            prediction = model.predict(test_np)
            self.result.setGeometry(QtCore.QRect(150, 415, 501, 51))
            self.result.setStyleSheet('background-color:rgba(0,0,0,0.5);\n''color:white;\n''border-radius:25px')
            self.result.setText('     Successfully marked ' + str(prediction[0]) + '!')
            self.delay = QTimer()
            self.delay.start(1500)
            self.delay.timeout.connect(self.resetLabel)
            df = pd.read_csv(master_path + 'Data/tableData.csv')
            sub = df.iloc[0, 0]
            path = df.iloc[0, 1]
            col = df.iloc[0, 2]
            df = pd.read_excel(path)
            df.set_index('MID', drop=False, inplace=True)
            for mid in df['MID']:
                if str(prediction[0]) == str(mid):
                    df.loc[mid, col] = 1
            df.to_excel(path,index=False)
        except cv2.error:
            self.result.setGeometry(QtCore.QRect(150, 415, 501, 51))
            self.result.setStyleSheet('background-color:rgba(0,0,0,0.5);\n''color:white;\n''border-radius:25px')
            self.result.setText('                  Failed to mark!')
            self.delay = QTimer()
            self.delay.start(1500)
            self.delay.timeout.connect(self.resetLabel)

    def setupUi(self, attendWindow):
        attendWindow.setObjectName('attendWindow')
        attendWindow.resize(800, 480)
        attendWindow.setStyleSheet('background-color:rgb(255,255,255)')
        self.liveCam = QtWidgets.QLabel(attendWindow)
        self.liveCam.setGeometry(QtCore.QRect(30, 80, 371, 371))
        self.liveCam.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.liveCam.setText('')
        self.liveCam.setObjectName('liveCam')
        font = QtGui.QFont()
        font.setFamily('Segoe UI Semibold')
        font.setPointSize(16)
        self.closeButton = QtWidgets.QPushButton(attendWindow)
        self.closeButton.setGeometry(QtCore.QRect(420, 390, 171, 71))
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet('background-color:rgb(255,255,255);\n''color:rgb(0,127,255);\n''border-radius:10;\n''border: 3px solid rgb(0,127,255);')
        self.closeButton.setObjectName('closeButton')
        self.closeButton.clicked.connect(self.openAuth)
        self.closeButton.clicked.connect(attendWindow.close)
        self.verifyButton = QtWidgets.QPushButton(attendWindow)
        self.verifyButton.setGeometry(QtCore.QRect(610, 390, 171, 71))
        self.verifyButton.setFont(font)
        self.verifyButton.setStyleSheet('background-color:rgb(0,127,255);\n''color:rgb(255,255,255);\n''border-radius:10;')
        self.verifyButton.setObjectName('verifyButton')
        self.verifyButton.clicked.connect(self.verifyFace)
        self.legend = QtWidgets.QLabel(attendWindow)
        self.legend.setGeometry(QtCore.QRect(30, 20, 311, 41))
        self.legend.setFont(font)
        self.legend.setObjectName('legend')
        font.setPointSize(18)
        self.result = QtWidgets.QLabel(attendWindow)
        self.result.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.result.setFont(font)
        self.result.setStyleSheet('background-color:rgba(0,0,0,0);\n''color:white;\n''border-radius:25px')
        self.result.setFrameShape(QtWidgets.QFrame.Box)
        self.result.setObjectName('result')
        font.setPointSize(20)
        self.title = QtWidgets.QLabel(attendWindow)
        self.title.setGeometry(QtCore.QRect(430, 20, 251, 51))
        self.title.setFont(font)
        self.title.setObjectName('title')
        self.line_1 = QtWidgets.QFrame(attendWindow)
        self.line_1.setGeometry(QtCore.QRect(420, 70, 361, 20))
        self.line_1.setLineWidth(2)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName('line_1')
        self.line_2 = QtWidgets.QFrame(attendWindow)
        self.line_2.setGeometry(QtCore.QRect(420, 365, 361, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName('line_2')
        font.setFamily('Segoe UI Semilight')
        font.setPointSize(14)
        self.desc = QtWidgets.QLabel(attendWindow)
        self.desc.setGeometry(QtCore.QRect(420, 80, 361, 111))
        self.desc.setFont(font)
        self.desc.setObjectName('desc')
        self.result.raise_()
        self.retranslateUi(attendWindow)
        QtCore.QMetaObject.connectSlotsByName(attendWindow)

    def retranslateUi(self, attendWindow):
        _translate = QtCore.QCoreApplication.translate
        attendWindow.setWindowTitle(_translate('attendWindow', 'Frame'))
        self.closeButton.setText(_translate('attendWindow', 'Close'))
        self.verifyButton.setText(_translate('attendWindow', 'Verify'))
        self.title.setText(_translate('attendWindow', 'Take attendance'))
        self.desc.setText(_translate('attendWindow', 'Show your face and press on verify\n''button and wait till a popup shows.\n''Confirm it and pass the device.'))
        self.legend.setText(_translate('attendWindow', 'Verify your face below'))

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QFrame()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())